### PR TITLE
177 Improve and simplify quote text objects

### LINKED ISSUE #177: Edge case of VimL comments fails
When operating on a block of VimL like the following,

```VimL
" ============================================================================
" SECTION: "The Section Title"
" ============================================================================
```

positioning the cursor on, say, `Title` and executing the macro `ci"` results in unexpected behavior. Specifically, the innards of the first set of quotes are deleted and `Insert` mode is entered there.

Just reporting an edge case that needs to be addressed.

### PR DESCRIPTION
**Pull request by wellle**
>Instead of halfway scanning the cursor line for quotation characters, we
now just count how many there are before, after and on the cursor to
decide at what rate to iterate quote targets and whether to skip
initially per direction.

Close #177

I went through all the cases we are currently able to recognize (it should be better than before) and tried to keep it compatible in most places and made some minor changes where I thought it makes sense. There should be no big surprises here, but if anyone finds any glitches, please let me know.

### CODE REVIEW

**Comment by omnikron** [comment]
@wellle howdy! I am encountering an error with `'` and `"` targets since updating to the latest targets.vim. For example, running `ci'` with the cursor anywhere on a line including a `'` delimited string like `'expires_at is null or expires_at > ?'` causes a crash with the following [error](https://gist.github.com/omnikron/3b21a2f838939c5d697ec185587d1e94). 

Only `'` and `"` seem to be affected (`ci_` still works fine for example).

* My [.vimrc](https://github.com/omnikron/dotvim/blob/b9aa6ac88bf18008ad07b2d5a1cce90b18c32997/.vimrc)
* Output of [vim --version](https://gist.github.com/omnikron/d9b8c1ef754557856200cc565c3e8d31) 

The same thing happens with all my other plugins turned off. Checking out the commit prior to this pull request (680eab3) resolves the issue.

 Let me know if I can provide any more debugging info. And say hi to everybody for me! 😁

**Comment by wellle** [comment]
Oh hey good to hear from you! We just landed in Thailand and I’ll make sure to look into this soon! Just in case I’d have trouble to reproduce, can you gist me a full file where it happens? Is in important to invoke the command in a particular place?

**Comment by wellle** [comment]
@omnikron: I see you have this issue with Vim 7.4 (thanks for the `--version` output) and I managed to reproduce it with Vim 7.3. I opened #196 to hopefully fix it. Could you checkout branch `195-fix-substring` and confirm that `ci'` works again? If so I'll merge it. 👍

**Comment by omnikron** [comment]
@wellle that has fixed it. You are basically a wizard. I love this plugin – use it every day, and always remember you first launching it.

Have a great trip! Should there be arm-wrestling, well...[win one for the gipper](https://www.youtube.com/watch?v=0CCwxMvXPZo) 💪

**Comment by wellle** [comment]
Merged, thanks again! ❤️

**Pull request merged**
