### PR TITLE
Fix three typos in the documentation

### PR DESCRIPTION
**Pull request by balta2ar**

### CODE REVIEW

**Comment by wellle** [comment]
@balta2ar: Thank you, this looks good and I will merge it soon. Do you want to fix the `ci"` issue you noted in https://github.com/wellle/targets.vim/pull/153#discussion_r74574349 here too?

**Comment by wellle** [comment]
@balta2ar: I noticed that you only changed the typos in the docs. Did you also check if they are present in the readme? If so can you fix them there too? Thanks!

**Comment by balta2ar** [comment]
@wellle Done!

**Comment by wellle** [comment]
Thank you!

**Pull request merged**
